### ISSUE TITLE
duckduckgo.com

### ISSUE THREAD

**Issue by spirillen** [hl2guide/All-in-One-Customized-Adblock-List#68]
Hi even those I'm a huge fan of [duckduckgo.com](duckduckgo.com) I can see you have whitelisted them ->
https://github.com/hl2guide/All-in-One-Customized-Adblock-List/blob/4be5bca6f56156213a34d6b6a656342680592a9a/2.9%20BETA%202020/whitelist.txt#L7

What I don't know is, is these rules WildCard rules, Like delete `/*.duckduckgo\.com$/`?

If this is the case you might like to do something about this rule as that would rule out `improving.duckduckgo.com` which is used for tracking.

```
dig axfr rpz.mypdns.cloud @axfr.ipv4.mypdns.cloud -p 5353 | grep -E "duckduckgo\.com"
improving.duckduckgo.com.rpz.mypdns.cloud. 345600 IN CNAME .
```

https://github.com/mypdns/matrix/blob/0bcbfc52a5e87e6bc462d337106e154eadea9d35/source/tracking/wildcard.list#L240

**Comment by hl2guide** [comment]
For duckduckgo I'd recommend just adding to whitelist and not sweating it.

I recommend this since duckduckgo is a welcome change to the invasive search engines like google.com and bing.com which are both bad for privacy and data collection.

I now use https://duckduckgo.com/lite/
since it is the lightest I've found, has not ads, doesn't censor results and is text-only.

I'd also suggest you check out qwant.com as an option.

**Comment by spirillen** [comment]
Hi @hl2guide 

I thinks you misunderstood my message, it wasn't a question for why you whitelisting DDG, as I solely use them my self.

The questions was, whether the whitelist also would whitelist `improving.duckduckgo.com` which is considered as tracking by most of those I compare my own records with and trust for doing a good solid work.
